version: '3.7'

services:
  frontend:
    container_name: ahc_frontend
    build: ./ahc_frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 7001:7001
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start